name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4   # uses actions from the repository
      with:
        go-version: '1.21.0' # pass input parameter of configuration options

    - name: Debug File Permissions Before Cache Restore
      run: |
        echo "Listing ~/go/pkg/mod contents (if exists):"
        if [ -d "~/go/pkg/mod" ]; then
          ls -al ~/go/pkg/mod
        else
          echo "Directory ~/go/pkg/mod does not exist."
        fi

    - name: Cache Go Modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      run: go build -v ./...

    - name: Test
      run: make test

    # Debug Log step to check environment and state
    - name: Debug Log
      run: |
        echo "Current directory:"
        pwd
        echo "List files in workspace:"
        ls -al
        echo "Environment variables:"
        env
