name: Release to Docker Hub

on:
  workflow_run:
    workflows: ["ci-test"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'

      - name: Install Dependencies
        run: |
          go mod tidy
          go mod vendor

      - name: Debug Log
        run: |
          echo "Current directory:"
          pwd
          echo "List files in workspace:"
          ls -al
          echo "Environment variables:"
          env

      - name: Build Inventory Binary
        run: make build_inventory_service

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/rental-inventory-service:1.0.0 .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/rental-inventory-service:1.0.0
